# Compose stack for running backend/frontend with an external MySQL instance in development
version: '3'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: development
      DB_HOST: ${EXTERNAL_DB_HOST}
      DB_PORT: ${EXTERNAL_DB_PORT:-3306}
      DB_NAME: ${EXTERNAL_DB_NAME}
      DB_USERNAME: ${EXTERNAL_DB_USERNAME}
      DB_PASSWORD: ${EXTERNAL_DB_PASSWORD}
      DB_DIALECT: mysql
      JWT_SECRET: dev-admin-secret
      JWT_USER_SECRET: dev-user-secret
      ADMIN_CREDENTIALS_JSON: >-
        [{"username":"admin","password":"admin123"}]
      ALLOWED_ORIGINS: http://localhost,http://localhost:8080
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
      args:
        REACT_APP_API_BASE_URL: "/api"
    ports:
      - "80:80"
    links:
      - "backend:local"
    depends_on:
      - backend
